export { default as PanelCSS } from './Panel.module.css'
export { default as AuthFormCSS } from './AuthForm.module.css'
export { default as SidenavCSS } from './Sidenav.module.css'
export { default as MainLayoutCSS } from './MainLayout.module.css'
export { default as TuzCSS } from './Tuz.module.css'
export { default as AritmaCSS } from './Aritma.module.css'
export { default as SabitlerCSS } from './Sabitler.module.css'