import Head from "next/head";
import { User, Guest } from "@/components";
import styles from "@/styles/Home.module.css";
import { getSession } from "next-auth/react";

export default function Home({ session }) {
  return (
    <>
      <Head>
        <title>Arıtma Kontrol Takip Sistemi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{session ? <User session={session}/> : <Guest />}</main>
    </>
  );
}

export const getServerSideProps = async ({ req }) => {
  const session = await getSession({ req });

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};
