import { Sidenav } from ".";
import styles from "../styles/MainLayout.module.css";
import Head from "next/head";

function Layout({ children, session }) {
  return (
    <>
      <Head>
        <title>Arıtma Kontrol Takip Sistemi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.layout}>
        <div>
          <div className="d-flex">
            <aside className="position-sticky">
              <Sidenav session={session} />
            </aside>
            <aside className="container">{children}</aside>
          </div>
        </div>
      </div>
    </>
  );
}

export default Layout;
