import { Sidenav } from ".";
import { SidenavCSS, MainLayoutCSS } from "@/styles";
import Head from "next/head";
import { RiMenu2Fill } from "react-icons/ri";
import { useState } from "react";

function Layout({ children, session }) {
  const [toggled, setToggled] = useState(false);
  const handleToggleSidebar = () => {
    const wrapper = document.getElementById("wrapper");
    wrapper.classList.toggle("toggled");

    if (toggled === true) {
      setToggled(false);
    } else {
      setToggled(true);
    }
  };

  return (
    <div className="body html">
      <Head>
        <title>Arıtma Kontrol Takip Sistemi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="wrapper">
        <div id="sidebar-wrapper">
          <Sidenav session={session} />
        </div>

        <div id="page-content-wrapper">
          <span style={{cursor: 'pointer'}} className="fs-3" onClick={handleToggleSidebar}>
            <RiMenu2Fill className={SidenavCSS.sideToggleMenu}/>
          </span>
          <div className="container d-flex flex-column">
            <div className="row">
              <div className="col-lg-12">{children}</div>
            </div>
          </div>
        </div>
      </div>

      {/* <div className={styles.layout}>
        <div>
          <div className="d-flex">
            <aside className="position-sticky">
              <Sidenav session={session} />
            </aside>
            <main className="container">{children}</main>
          </div>
        </div>
      </div> */}

      <style jsx global>{`
        @media only screen and (max-width: 720px) {
          html {
            overflow: hidden;
          }
        }

        .menu-hover::hover {
          opacity: "50%";
        }

        #wrapper {
          padding-left: 0;
          -webkit-transition: all 0.5s ease;
          -moz-transition: all 0.5s ease;
          -o-transition: all 0.5s ease;
          transition: all 0.5s ease;
        }

        #wrapper.toggled {
          padding-left: 250px;
        }

        #sidebar-wrapper {
          z-index: 1000;
          position: fixed;
          left: 250px;
          width: 0;
          height: 100%;
          margin-left: -250px;
          overflow-y: auto;
          background: #f8f9fa;
          -webkit-transition: all 0.5s ease;
          -moz-transition: all 0.5s ease;
          -o-transition: all 0.5s ease;
          transition: all 0.5s ease;
        }

        #wrapper.toggled #sidebar-wrapper {
          width: 250px;
        }

        #page-content-wrapper {
          width: 100%;
          position: absolute;
          padding: 15px;
        }

        #wrapper.toggled #page-content-wrapper {
          position: absolute;
          margin-right: -250px;
        }

        /* Sidebar Styles */

        .sidebar-nav {
          position: absolute;
          top: 0;
          width: 250px;
          margin: 0;
          padding: 0;
          list-style: none;
        }

        .sidebar-nav li {
          text-indent: 20px;
          line-height: 40px;
        }

        .sidebar-nav li a {
          display: block;
          text-decoration: none;
          color: #999999;
        }

        .sidebar-nav li a:hover {
          text-decoration: none;
          color: #fff;
          background: rgba(255, 255, 255, 0.2);
        }

        .sidebar-nav li a:active,
        .sidebar-nav li a:focus {
          text-decoration: none;
        }

        .sidebar-nav > .sidebar-brand {
          height: 65px;
          font-size: 18px;
          line-height: 60px;
        }

        .sidebar-nav > .sidebar-brand a {
          color: #999999;
        }

        .sidebar-nav > .sidebar-brand a:hover {
          color: #fff;
          background: none;
        }

        @media (min-width: 768px) {
          #wrapper {
            padding-left: 250px;
          }

          #wrapper.toggled {
            padding-left: 0;
          }

          #sidebar-wrapper {
            width: 250px;
          }

          #wrapper.toggled #sidebar-wrapper {
            width: 0;
          }

          #page-content-wrapper {
            padding: 20px;
            position: relative;
          }

          #wrapper.toggled #page-content-wrapper {
            position: relative;
            margin-right: 0;
          }
        }
      `}</style>
    </div>
  );
}

export default Layout;
